### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [ruby7sapphire/fhp-splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by ruby7sapphire** [comment]
Thanks for the suggestion. I implemented the mobile meta tag, along with various style and layout tweaks at 807c61d962c4d71732e11829c15f5c9e80694000.

**Comment by kenmazaika** [comment]
Looks solid, @ruby7sapphire.  Great work adjusting the bootstrap classes to make the styling look perfect, too!    👍

**Comment by ruby7sapphire** [comment]
Thank you @kenmazaika!
